import type { Metadata } from "next";
import { Raleway } from 'next/font/google';
import Image from 'next/image';
import './globals.css';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="eltaskyline">
          <Image src="/elta.svg" fill={true} alt="" />
        </div>
        <main className={raleway.className}>{children}</main>
      </body>
    </html>
  );
}
